### ISSUE TITLE
Extension broken following lastfm's recent site changes.

### ISSUE THREAD

**Issue by dcmaradiaga** [xxdavid/lastfm-friends-who-listen#1]
Extension stays on "Loading, please wait..." message. Using Chrome version 52.0.2743.116

**Comment by zvonicek** [comment]
I also experience a problem on Firefox 47.0.1, but it doesn't even show the "Loading" message.

**Comment by xxdavid** [comment]
Hey guys, I know about the issue. It's because Last.fm doesn't include your username in the header anymore. It'll be easy to fix. I just didn't have time for it yet, will do it today or tomorrow. (Finally someone uses Github instead of that horrible Get Satisfaction.)

**Comment by xxdavid** [comment]
So I finally implemented the fix. But Last.fm API gives me error 500 half of the time. I don't know where's the problem but it should be on Last.fm's end. I'll wait till tomorrow to if see if it'll be working. Thank you for patience.

![Error 500](https://cloud.githubusercontent.com/assets/3393339/17833397/5e293dfc-671c-11e6-82dc-c1236bfbf3ee.png)

**Comment by xxdavid** [comment]
It's working and I pushed the fix to master but I'm not gonna release it yet. I'll do a bit of refactoring before. Release will be probably tomorrow, finally.

**Comment by James-Joul** [comment]
That's great, thank you! I've been lost without this feature.

**Comment by xxdavid** [comment]
Done. I submitted the update to both stores. It should be live in an hour in Chrome Webstore and maybe tomorrow in Firefox Add-ons (needs human approval). The refactoring of `storage.js` introduces a bit different format of storing preferences so you'll probably have to set them again, sorry.
