### ISSUE TITLE
the plugin has stopped loading the data

### ISSUE THREAD

**Issue by RadMushroom** [xxdavid/lastfm-friends-who-listen#11]
Couple days ago the plugin has stopped loading the data in Google Chrome. Clearing cache in browser and reinstalling plugin didn't help.
![photo_2018-08-08_12-27-26](https://user-images.githubusercontent.com/11655207/43829110-d8040eb6-9b06-11e8-8d1a-2683e9e1d5a8.jpg)

**Comment by xxdavid** [comment]
Hi, sorry for the late reply. It's working for me. Could you please try another browser (Firefox, Opera, Vivaldi) if it works? Did you clearing cache with the `localStorage.clear()` command?

**Comment by xxdavid** [comment]
https://github.com/xxdavid/lastfm-friends-who-listen/issues/9#issuecomment-368315556

**Comment by xxdavid** [comment]
Hope it helped.
