### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by RaylaLe100** [xxdavid/lastfm-friends-who-listen#14]
Hi !
The extention stopped working for me a month or two ago I guess, I don't know what caused it and I don't know if everyone has the problem or if it's only me.
There is no suspicious message in the console when I'm on an artist page, so I'm at point 0 right now. If anyone have the same problem it would be cool to help

**Comment by hans-juergen** [comment]
If you have become a subscriber and/or got the new Last.fm website design in the meantime, this browser extension will currently not work anymore, only with the old website design.

**Comment by RaylaLe100** [comment]
I'm not a subscriber, and the design haven't change recently as far as I remember. Is there a way to see if I use the old/new design?

**Comment by hans-juergen** [comment]
See the official announcement thread on Get Satisfaction with screenshots:

https://getsatisfaction.com/lastfm/topics/website-design-update-rolling-out-today

**Comment by xxdavid** [comment]
Fixed by #15. It should be working now (updated Firefox version is in the store, Chrome version is waiting for a review).
