### ISSUE TITLE
Porting to MS Edge?

### ISSUE THREAD

**Issue by hans-juergen** [xxdavid/lastfm-friends-who-listen#2]
Hi David, you probably know that Microsoft has enabled Chrome extension support in Edge with the latest Windows 10 Anniversary update a few days ago. They also have published a tool in the Windows 10 app store now for porting a Chrome extension, see this article for more info and the link:

http://news.softpedia.com/news/microsoft-launches-app-to-convert-chrome-extensions-to-windows-10-edge-browser-507034.shtml

As you already ported your extension to Firefox (which also supports Chrome extensions now directly since v48), maybe you could try out this tool and see if it works?

**Comment by xxdavid** [comment]
Hi! At first, thank you for using GitHub Issues, it's easier for me than Get Satisfaction.

Yes I heard something about Edge supporting Chrome extensions but didn't study it further. The thing is I don't like Windows much and I don't use them. I have access to two Windows machines but they're running Windows 7 and 8.1. I could probably use some virtual machine but I don't know if it's worth it. There's a hassle with updating the extension in two stores already. I don't know anyone who actually uses Edge. Do _you_?

**Comment by hans-juergen** [comment]
For testing purposes from time to time, my main browser is Chrome at the moment, and I recently checked out Opera on my oldest PCs again. The problem with Edge is that all developers I know hate Microsoft, but 90% of the normal users have Windows on their computers. So there always is a big acceptance gap between them, not helping anyone in my opinion and blocking further development, testing and usage.

But it's been like that since I joined open source projects about 20 years ago, so I'm used to it. Maybe someone will develop a similar wrapper tool for the Google Chrome app store in Edge like there is one for Firefox and Opera now, then all Chrome extensions can be installed, no matter if they have been individually ported or not.

**Comment by xxdavid** [comment]
Haha, "all developers I know hate Microsoft" :D. I didn't say I hate Microsoft, they have some great products, Office for instance, and they are very active in the open source community since Nadella is on board, but their OS really sucks for development. I don't say it's bad for everything, it may be great for normal things (although I think Mac is a better solution for most of the things, but also more expensive...) but it's not for developers. My opinion. 

About the port. I will consider it. For you. As I don't really think anyone else uses Edge. :D You really helped me with support and all the other things. Thank you! :) 

Btw, you participate in open source for 20 years? That's much more that I'm doing development. :D What exactly do you do (just curious)?

**Comment by hans-juergen** [comment]
I'm not a Windows "fan" either, I only see it from a user or in this case Last.fm moderator perspective. Windows 10 will probably be the most used OS in the future, Microsoft claims that it is installed on 350 million devices already after one year of the free upgrade option. And most users do not care for testing and installing other browsers, they use what is there, sometimes they are not allowed to use something else, too, e.g. at work. Edge would be the first MS browser that can scrobble with the Chrome extensions, that is what makes it interesting for a site like Last.fm which depends on many users scrobbling their data to them. So I also suggested porting to the developers of the Chrome scrobbler extensions, not only to you. ;-)

I started helping with beta testing new versions of a DOS email and news program called CrossPoint or XP back in the '90s, as far as I remember, and also helped other users in the related forums. Then I got interested in audio codec development and helped the FAAC project for quite a long time, until all developers got real jobs. I'm not a programmer though, only beta tester, forum mod, developer translator etc. Somewhere in between I also was part of the DMOZ project, i.e. Mozilla creating an open source web directory.

**Comment by hans-juergen** [comment]
By the way, MS Edge will be using the Chromium engine for its next version as well, like e.g. Opera:

https://www.windowscentral.com/hands-new-chromium-powered-version-microsoft-edge

I'm looking forward to finally use some Chrome extensions with it like the Last.fm web scrobbler and your extension, too.

**Comment by xxdavid** [comment]
Great!
Does it mean Edge will support Chrome extensions (as Opera or Vivaldi does), or will the devs (me in this case) need to submit the extensions to a separate store (that's Firefox's case)?

**Comment by hans-juergen** [comment]
I hope the former (directly from the Chrome store), but don't know more details yet. It may take some more weeks and months before Microsoft actually releases Edge with a Chromium engine, too.

The current Edge version is pretty good as well, both in performance and handling, e.g. finally being able to manage bookmarks properly and adding extensions from the MS store. Most of the time I'm using Opera now, but Edge is handy when I set up a new PC with Windows 10.

**Comment by xxdavid** [comment]
It seems Edge can now load extensions from the Chrome store so I am closing this.
