### ISSUE TITLE
Users with no avatar don't display correctly

### ISSUE THREAD

**Issue by Hum4n01d** [xxdavid/lastfm-friends-who-listen#21]
Example: ![image](https://user-images.githubusercontent.com/17228477/104136894-e422b880-534d-11eb-8f11-63106ef16f91.png)

**Comment by xxdavid** [comment]
Hi, thank you for reporting this. I noticed it too but I was too lazy to fix it, haha. I'll try to fix it in the next version (but I don't know when).
