### ISSUE TITLE
(Idea) Show your statistics in the list

### ISSUE THREAD

**Issue by Hum4n01d** [xxdavid/lastfm-friends-who-listen#22]
It would be nice if you could see your own statistics in the list as well as your friends (to compare)

I may take a shot at adding it if it isn't too complicated 😁

**Comment by xxdavid** [comment]
Hi, this is a good idea, I think it might be useful! I'm gonna look at your pull request.

**Comment by xxdavid** [comment]
Implemented! (I mistyped number of this issue in the commit message, lol, so I'm closing this issue manually.)
