### ISSUE TITLE
Extension Has Stopped Working

### ISSUE THREAD

**Issue by James-Joul** [xxdavid/lastfm-friends-who-listen#3]
Hey David. 

Today the Friends Who Listen extension stopped working (using Chrome) and has disappeared entirely from Last.fm pages. We just found out (on the GetSatisfaction forums) that Last.fm moved to HTTPS earlier today and this is the cause of the issue. Would it be possible to update the extension? It's one of my favourite features on Last.fm and I can't imagine living without it.

https://getsatisfaction.com/lastfm/topics/-friend-listening-to-extension-disappeared

Thanks for your time,

James

**Comment by xxdavid** [comment]
Hi James,
thank you for your investigation. I'll update the extension today or tomorrow. :)
