### ISSUE TITLE
Firefox version not working

### ISSUE THREAD

**Issue by dattrue** [xxdavid/lastfm-friends-who-listen#4]
Hi, the Firefox version is still not working even though the Chrome version is working fine again, is the update going to be up on the official Mozilla extensions site as well? If so, any idea when that might be? Sorry for bothering you with such a minuscule problem!

**Comment by xxdavid** [comment]
Hi, the Firefox addon is still in the review process and there are currently 160 addons in front of mine. You will have to wait a few more days probably.

**Comment by xxdavid** [comment]
I can give you the `.xpi` so you can install it yourself. Would you be interested?

**Comment by dattrue** [comment]
If it's not too much trouble, I would love that! I love this extension and being so used to having it has made these couple of days slightly difficult. Thank you for this fine feature!

**Comment by xxdavid** [comment]
[friends-who-listen.xpi.zip](https://github.com/xxdavid/lastfm-friends-who-listen/files/784995/friends-who-listen.xpi.zip)
Unzip it and install the `.xpi`. It's not signed so you have to disable the signature check in Firefox somehow (it may not be possible in the new versions of Firefox, I don't know) or use Firefox Nightly where the check is disabled by default.

**Comment by xxdavid** [comment]
Finally, the update has been approved. You can update the extension in Add-ons Manager.
