### ISSUE TITLE
app is rendered multiple times when using AdBlock Plus

### ISSUE THREAD

**Issue by dcmaradiaga** [xxdavid/lastfm-friends-who-listen#5]
I uploaded a video of what happens here: https://youtu.be/e62d-GOFQgo

 I've since switched to uBlock Origin and I no longer get this issue, but I thought it was important to mention either way.

**Comment by dcmaradiaga** [comment]
Nevermind, It's now happening on uBlock as well.

**Comment by xxdavid** [comment]
Hi, I'm not really a fan of ad blockers (in fact I think using them is pretty bad), so this is no priority for me. Maybe I'll look into it when I have some time, someday.
