### ISSUE TITLE
Script not responding, Firefox freezing

### ISSUE THREAD

**Issue by dattrue** [xxdavid/lastfm-friends-who-listen#6]
Since yesterday, 99% of the time when I go to an artist/album/track page, Firefox freezes up and a short while later I get a popup saying that the friends who listen script is not responding, asking me whether I'd like to wait for it to finish, look at the script or stop it. Waiting never works, it just keeps freezing and the same thing happens whenever I go to a different page. Stopping the script makes Firefox responsive again but obviously then I can't see my friends' listening.

I prefer this addon to Last.fm's official feature, thank you for this, but does this sound like a problem that's on my end or is there an issue in the addon itself? The Chrome version seems to be working ok.

**Comment by xxdavid** [comment]
Hi,

the worst design choice I made for Friends Who Listen was using `localStorage` for cache. Ninety percent reported bugs come out of this and I think it's also the source of your problem. I would rewrite the extension to use something else like `IndexedDB` but I don't have time for it...
However, the workaround is pretty simple – open Console (Ctrl+Shift+K or Cmd+Opt+K if you're on Mac), type there `localStorage.clear()` and hit enter.

Hope it helps. :)

**Comment by xxdavid** [comment]
I forget to mention that you have to clear the `localStorage` on Last.fm (go to Last.fm and then open the console...).

**Comment by dattrue** [comment]
I did what you said and it seems to be working correctly again. Thanks a lot for the very quick  and helpful response!

**Comment by xxdavid** [comment]
I was happy to help. :)
