### ISSUE TITLE
Cannot be installed in Firefox

### ISSUE THREAD

**Issue by marsjaninzmarsa** [xxdavid/lastfm-friends-who-listen#7]
Not compatible with Nightly 56.0a1, probably e10s issue, switch to WebExtensions?

**Comment by xxdavid** [comment]
Hi, thank you for reporting. :) I'm having a holiday but maybe I'll find some time on Friday. 
I haven't dug into WebExtensions yet. Does it mean that the Chrome version is now runnable in Firefox (if packaged with jpm)?

**Comment by xxdavid** [comment]
It is compatible now. You can download it from the store.
